// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package automock

import (
	context "context"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SystemsService is an autogenerated mock type for the SystemsService type
type SystemsService struct {
	mock.Mock
}

// CreateManyIfNotExistsWithEventualTemplate provides a mock function with given fields: ctx, applicationInputs, systemToTemplateMapping
func (_m *SystemsService) CreateManyIfNotExistsWithEventualTemplate(ctx context.Context, applicationInputs []model.ApplicationRegisterInput, systemToTemplateMapping []string) error {
	ret := _m.Called(ctx, applicationInputs, systemToTemplateMapping)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.ApplicationRegisterInput, []string) error); ok {
		r0 = rf(ctx, applicationInputs, systemToTemplateMapping)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
