// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// PlanValidator is an autogenerated mock type for the PlanValidator type
type PlanValidator struct {
	mock.Mock
}

// IsPlanSupport provides a mock function with given fields: planID
func (_m *PlanValidator) IsPlanSupport(planID string) bool {
	ret := _m.Called(planID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(planID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
