// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/control-plane/components/provisioner/internal/apperrors"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-project/control-plane/components/provisioner/internal/model"
)

// Provisioner is an autogenerated mock type for the Provisioner type
type Provisioner struct {
	mock.Mock
}

// DeprovisionCluster provides a mock function with given fields: cluster, operationId
func (_m *Provisioner) DeprovisionCluster(cluster model.Cluster, operationId string) (model.Operation, apperrors.AppError) {
	ret := _m.Called(cluster, operationId)

	var r0 model.Operation
	if rf, ok := ret.Get(0).(func(model.Cluster, string) model.Operation); ok {
		r0 = rf(cluster, operationId)
	} else {
		r0 = ret.Get(0).(model.Operation)
	}

	var r1 apperrors.AppError
	if rf, ok := ret.Get(1).(func(model.Cluster, string) apperrors.AppError); ok {
		r1 = rf(cluster, operationId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// ProvisionCluster provides a mock function with given fields: cluster, operationId
func (_m *Provisioner) ProvisionCluster(cluster model.Cluster, operationId string) apperrors.AppError {
	ret := _m.Called(cluster, operationId)

	var r0 apperrors.AppError
	if rf, ok := ret.Get(0).(func(model.Cluster, string) apperrors.AppError); ok {
		r0 = rf(cluster, operationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apperrors.AppError)
		}
	}

	return r0
}
