// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"
	gqlclient "github.com/kyma-incubator/compass/components/kyma-adapter/internal/gqlclient"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CreateBundleInstanceAuth provides a mock function with given fields: ctx, tenant, input
func (_m *Client) CreateBundleInstanceAuth(ctx context.Context, tenant string, input gqlclient.BundleInstanceAuthInput) error {
	ret := _m.Called(ctx, tenant, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gqlclient.BundleInstanceAuthInput) error); ok {
		r0 = rf(ctx, tenant, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBundleInstanceAuth provides a mock function with given fields: ctx, tenant, input
func (_m *Client) DeleteBundleInstanceAuth(ctx context.Context, tenant string, input gqlclient.BundleInstanceAuthInput) error {
	ret := _m.Called(ctx, tenant, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gqlclient.BundleInstanceAuthInput) error); ok {
		r0 = rf(ctx, tenant, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApplicationBundles provides a mock function with given fields: ctx, appID, tenant
func (_m *Client) GetApplicationBundles(ctx context.Context, appID string, tenant string) ([]*graphql.BundleExt, error) {
	ret := _m.Called(ctx, appID, tenant)

	var r0 []*graphql.BundleExt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*graphql.BundleExt, error)); ok {
		return rf(ctx, appID, tenant)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*graphql.BundleExt); ok {
		r0 = rf(ctx, appID, tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graphql.BundleExt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, appID, tenant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantByInternalIDQuery provides a mock function with given fields: ctx, tenantID
func (_m *Client) TenantByInternalIDQuery(ctx context.Context, tenantID string) (*graphql.Tenant, error) {
	ret := _m.Called(ctx, tenantID)

	var r0 *graphql.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*graphql.Tenant, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *graphql.Tenant); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graphql.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBundleInstanceAuth provides a mock function with given fields: ctx, tenant, input
func (_m *Client) UpdateBundleInstanceAuth(ctx context.Context, tenant string, input gqlclient.BundleInstanceAuthInput) error {
	ret := _m.Called(ctx, tenant, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gqlclient.BundleInstanceAuthInput) error); ok {
		r0 = rf(ctx, tenant, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
