// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OperationCreator is an autogenerated mock type for the OperationCreator type
type OperationCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *OperationCreator) Create(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOperationCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewOperationCreator creates a new instance of OperationCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOperationCreator(t mockConstructorTestingTNewOperationCreator) *OperationCreator {
	mock := &OperationCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
