// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/kyma-incubator/compass/components/provisioner/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// InstallKyma provides a mock function with given fields: kubeconfigRaw, release
func (_m *Service) InstallKyma(kubeconfigRaw string, release model.Release) error {
	ret := _m.Called(kubeconfigRaw, release)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.Release) error); ok {
		r0 = rf(kubeconfigRaw, release)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
