BEGIN;

ALTER TABLE formations
    ADD COLUMN state TEXT NOT NULL CHECK ( state IN ('INITIAL', 'READY', 'CREATE_ERROR', 'DELETE_ERROR', 'DELETING')) DEFAULT 'READY',
    ADD COLUMN error JSONB;

COMMIT;
