// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"

	resource "github.com/kyma-incubator/compass/components/director/pkg/resource"
)

// EventDefService is an autogenerated mock type for the EventDefService type
type EventDefService struct {
	mock.Mock
}

// CreateInApplication provides a mock function with given fields: ctx, appID, in, spec
func (_m *EventDefService) CreateInApplication(ctx context.Context, appID string, in model.EventDefinitionInput, spec *model.SpecInput) (string, error) {
	ret := _m.Called(ctx, appID, in, spec)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, model.EventDefinitionInput, *model.SpecInput) string); ok {
		r0 = rf(ctx, appID, in, spec)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, model.EventDefinitionInput, *model.SpecInput) error); ok {
		r1 = rf(ctx, appID, in, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateInBundle provides a mock function with given fields: ctx, resourceType, resourceID, bundleID, in, spec
func (_m *EventDefService) CreateInBundle(ctx context.Context, resourceType resource.Type, resourceID string, bundleID string, in model.EventDefinitionInput, spec *model.SpecInput) (string, error) {
	ret := _m.Called(ctx, resourceType, resourceID, bundleID, in, spec)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, resource.Type, string, string, model.EventDefinitionInput, *model.SpecInput) string); ok {
		r0 = rf(ctx, resourceType, resourceID, bundleID, in, spec)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, resource.Type, string, string, model.EventDefinitionInput, *model.SpecInput) error); ok {
		r1 = rf(ctx, resourceType, resourceID, bundleID, in, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, resourceType, id
func (_m *EventDefService) Delete(ctx context.Context, resourceType resource.Type, id string) error {
	ret := _m.Called(ctx, resourceType, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, resource.Type, string) error); ok {
		r0 = rf(ctx, resourceType, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *EventDefService) Get(ctx context.Context, id string) (*model.EventDefinition, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.EventDefinition
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.EventDefinition); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EventDefinition)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByApplicationIDPage provides a mock function with given fields: ctx, appID, pageSize, cursor
func (_m *EventDefService) ListByApplicationIDPage(ctx context.Context, appID string, pageSize int, cursor string) (*model.EventDefinitionPage, error) {
	ret := _m.Called(ctx, appID, pageSize, cursor)

	var r0 *model.EventDefinitionPage
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string) *model.EventDefinitionPage); ok {
		r0 = rf(ctx, appID, pageSize, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EventDefinitionPage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = rf(ctx, appID, pageSize, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFetchRequests provides a mock function with given fields: ctx, eventDefIDs
func (_m *EventDefService) ListFetchRequests(ctx context.Context, eventDefIDs []string) ([]*model.FetchRequest, error) {
	ret := _m.Called(ctx, eventDefIDs)

	var r0 []*model.FetchRequest
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.FetchRequest); ok {
		r0 = rf(ctx, eventDefIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FetchRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, eventDefIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, resourceType, id, in, spec
func (_m *EventDefService) Update(ctx context.Context, resourceType resource.Type, id string, in model.EventDefinitionInput, spec *model.SpecInput) error {
	ret := _m.Called(ctx, resourceType, id, in, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, resource.Type, string, model.EventDefinitionInput, *model.SpecInput) error); ok {
		r0 = rf(ctx, resourceType, id, in, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateForApplication provides a mock function with given fields: ctx, id, in, specIn
func (_m *EventDefService) UpdateForApplication(ctx context.Context, id string, in model.EventDefinitionInput, specIn *model.SpecInput) error {
	ret := _m.Called(ctx, id, in, specIn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.EventDefinitionInput, *model.SpecInput) error); ok {
		r0 = rf(ctx, id, in, specIn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEventDefService interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventDefService creates a new instance of EventDefService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventDefService(t mockConstructorTestingTNewEventDefService) *EventDefService {
	mock := &EventDefService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
