// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"
import scenarioassignment "github.com/kyma-incubator/compass/components/director/internal/domain/scenarioassignment"

// EntityConverter is an autogenerated mock type for the EntityConverter type
type EntityConverter struct {
	mock.Mock
}

// ToEntity provides a mock function with given fields: assignment
func (_m *EntityConverter) ToEntity(assignment model.AutomaticScenarioAssignment) scenarioassignment.Entity {
	ret := _m.Called(assignment)

	var r0 scenarioassignment.Entity
	if rf, ok := ret.Get(0).(func(model.AutomaticScenarioAssignment) scenarioassignment.Entity); ok {
		r0 = rf(assignment)
	} else {
		r0 = ret.Get(0).(scenarioassignment.Entity)
	}

	return r0
}
