// Code generated by mockery v2.10.4. DO NOT EDIT.

package automock

import (
	tls "crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// CertificateCache is an autogenerated mock type for the CertificateCache type
type CertificateCache struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *CertificateCache) Get() *tls.Certificate {
	ret := _m.Called()

	var r0 *tls.Certificate
	if rf, ok := ret.Get(0).(func() *tls.Certificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Certificate)
		}
	}

	return r0
}
