// Code generated by mockery. DO NOT EDIT.

package automock

import (
	tls "crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// CertificateCache is an autogenerated mock type for the CertificateCache type
type CertificateCache struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *CertificateCache) Get() map[string]*tls.Certificate {
	ret := _m.Called()

	var r0 map[string]*tls.Certificate
	if rf, ok := ret.Get(0).(func() map[string]*tls.Certificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*tls.Certificate)
		}
	}

	return r0
}

// NewCertificateCache creates a new instance of CertificateCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateCache {
	mock := &CertificateCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
