// Code generated by mockery v2.5.1. DO NOT EDIT.

package automock

import (
	context "context"

	open_resource_discovery "github.com/kyma-incubator/compass/components/director/internal/open_resource_discovery"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// FetchOpenResourceDiscoveryDocuments provides a mock function with given fields: ctx, url
func (_m *Client) FetchOpenResourceDiscoveryDocuments(ctx context.Context, url string) (open_resource_discovery.Documents, error) {
	ret := _m.Called(ctx, url)

	var r0 open_resource_discovery.Documents
	if rf, ok := ret.Get(0).(func(context.Context, string) open_resource_discovery.Documents); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(open_resource_discovery.Documents)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
