// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/kyma-incubator/compass/components/director/pkg/resource"
)

// EntityTypeMappingProcessor is an autogenerated mock type for the EntityTypeMappingProcessor type
type EntityTypeMappingProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, resourceType, resourceID, entityTypeMappings
func (_m *EntityTypeMappingProcessor) Process(ctx context.Context, resourceType resource.Type, resourceID string, entityTypeMappings []*model.EntityTypeMappingInput) ([]*model.EntityTypeMapping, error) {
	ret := _m.Called(ctx, resourceType, resourceID, entityTypeMappings)

	var r0 []*model.EntityTypeMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, resource.Type, string, []*model.EntityTypeMappingInput) ([]*model.EntityTypeMapping, error)); ok {
		return rf(ctx, resourceType, resourceID, entityTypeMappings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, resource.Type, string, []*model.EntityTypeMappingInput) []*model.EntityTypeMapping); ok {
		r0 = rf(ctx, resourceType, resourceID, entityTypeMappings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EntityTypeMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, resource.Type, string, []*model.EntityTypeMappingInput) error); ok {
		r1 = rf(ctx, resourceType, resourceID, entityTypeMappings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEntityTypeMappingProcessor creates a new instance of EntityTypeMappingProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityTypeMappingProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityTypeMappingProcessor {
	mock := &EntityTypeMappingProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
