// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	formationassignment "github.com/kyma-incubator/compass/components/director/internal/domain/formationassignment"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// StatusService is an autogenerated mock type for the statusService type
type StatusService struct {
	mock.Mock
}

// SetFormationToErrorStateWithConstraints provides a mock function with given fields: ctx, _a1, errorMessage, errorCode, state, operation
func (_m *StatusService) SetFormationToErrorStateWithConstraints(ctx context.Context, _a1 *model.Formation, errorMessage string, errorCode formationassignment.AssignmentErrorCode, state model.FormationState, operation model.FormationOperation) error {
	ret := _m.Called(ctx, _a1, errorMessage, errorCode, state, operation)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Formation, string, formationassignment.AssignmentErrorCode, model.FormationState, model.FormationOperation) error); ok {
		r0 = rf(ctx, _a1, errorMessage, errorCode, state, operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWithConstraints provides a mock function with given fields: ctx, _a1, operation
func (_m *StatusService) UpdateWithConstraints(ctx context.Context, _a1 *model.Formation, operation model.FormationOperation) error {
	ret := _m.Called(ctx, _a1, operation)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Formation, model.FormationOperation) error); ok {
		r0 = rf(ctx, _a1, operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStatusService creates a new instance of StatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusService {
	mock := &StatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
