// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import context "context"
import mock "github.com/stretchr/testify/mock"

// ContextValueSetter is an autogenerated mock type for the ContextValueSetter type
type ContextValueSetter struct {
	mock.Mock
}

// WithValue provides a mock function with given fields: parent, key, val
func (_m *ContextValueSetter) WithValue(parent context.Context, key interface{}, val interface{}) context.Context {
	ret := _m.Called(parent, key, val)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, interface{}) context.Context); ok {
		r0 = rf(parent, key, val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}
