// Code generated by mockery v1.0.0
package automock

import graphql "github.com/kyma-incubator/compass/components/director/internal/graphql"
import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"

// EventAPIConverter is an autogenerated mock type for the EventAPIConverter type
type EventAPIConverter struct {
	mock.Mock
}

// MultipleInputFromGraphQL provides a mock function with given fields: in
func (_m *EventAPIConverter) MultipleInputFromGraphQL(in []*graphql.EventAPIDefinitionInput) []*model.EventAPIDefinitionInput {
	ret := _m.Called(in)

	var r0 []*model.EventAPIDefinitionInput
	if rf, ok := ret.Get(0).(func([]*graphql.EventAPIDefinitionInput) []*model.EventAPIDefinitionInput); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EventAPIDefinitionInput)
		}
	}

	return r0
}
