// Code generated by mockery. DO NOT EDIT.

package automock

import (
	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// EventDefinitionConverter is an autogenerated mock type for the EventDefinitionConverter type
type EventDefinitionConverter struct {
	mock.Mock
}

// ToGraphQL provides a mock function with given fields: in, spec, bundleRef
func (_m *EventDefinitionConverter) ToGraphQL(in *model.EventDefinition, spec *model.Spec, bundleRef *model.BundleReference) (*graphql.EventDefinition, error) {
	ret := _m.Called(in, spec, bundleRef)

	var r0 *graphql.EventDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.EventDefinition, *model.Spec, *model.BundleReference) (*graphql.EventDefinition, error)); ok {
		return rf(in, spec, bundleRef)
	}
	if rf, ok := ret.Get(0).(func(*model.EventDefinition, *model.Spec, *model.BundleReference) *graphql.EventDefinition); ok {
		r0 = rf(in, spec, bundleRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graphql.EventDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.EventDefinition, *model.Spec, *model.BundleReference) error); ok {
		r1 = rf(in, spec, bundleRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventDefinitionConverter creates a new instance of EventDefinitionConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventDefinitionConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventDefinitionConverter {
	mock := &EventDefinitionConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
