// Code generated by mockery. DO NOT EDIT.

package automock

import (
	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// IntegrationDependencyConverter is an autogenerated mock type for the IntegrationDependencyConverter type
type IntegrationDependencyConverter struct {
	mock.Mock
}

// ToGraphQL provides a mock function with given fields: in, aspects, aspectEventResourcesByAspectID
func (_m *IntegrationDependencyConverter) ToGraphQL(in *model.IntegrationDependency, aspects []*model.Aspect, aspectEventResourcesByAspectID map[string][]*model.AspectEventResource) (*graphql.IntegrationDependency, error) {
	ret := _m.Called(in, aspects, aspectEventResourcesByAspectID)

	if len(ret) == 0 {
		panic("no return value specified for ToGraphQL")
	}

	var r0 *graphql.IntegrationDependency
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.IntegrationDependency, []*model.Aspect, map[string][]*model.AspectEventResource) (*graphql.IntegrationDependency, error)); ok {
		return rf(in, aspects, aspectEventResourcesByAspectID)
	}
	if rf, ok := ret.Get(0).(func(*model.IntegrationDependency, []*model.Aspect, map[string][]*model.AspectEventResource) *graphql.IntegrationDependency); ok {
		r0 = rf(in, aspects, aspectEventResourcesByAspectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graphql.IntegrationDependency)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.IntegrationDependency, []*model.Aspect, map[string][]*model.AspectEventResource) error); ok {
		r1 = rf(in, aspects, aspectEventResourcesByAspectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIntegrationDependencyConverter creates a new instance of IntegrationDependencyConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationDependencyConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationDependencyConverter {
	mock := &IntegrationDependencyConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
