// Code generated by mockery. DO NOT EDIT.

package automock

import (
	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// OperationConverter is an autogenerated mock type for the OperationConverter type
type OperationConverter struct {
	mock.Mock
}

// MultipleToGraphQL provides a mock function with given fields: in
func (_m *OperationConverter) MultipleToGraphQL(in []*model.Operation) ([]*graphql.Operation, error) {
	ret := _m.Called(in)

	var r0 []*graphql.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func([]*model.Operation) ([]*graphql.Operation, error)); ok {
		return rf(in)
	}
	if rf, ok := ret.Get(0).(func([]*model.Operation) []*graphql.Operation); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graphql.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func([]*model.Operation) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOperationConverter creates a new instance of OperationConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationConverter {
	mock := &OperationConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
