// Code generated by mockery. DO NOT EDIT.

package automock

import (
	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// TenantBusinessTypeConverter is an autogenerated mock type for the TenantBusinessTypeConverter type
type TenantBusinessTypeConverter struct {
	mock.Mock
}

// ToGraphQL provides a mock function with given fields: in
func (_m *TenantBusinessTypeConverter) ToGraphQL(in *model.TenantBusinessType) *graphql.TenantBusinessType {
	ret := _m.Called(in)

	var r0 *graphql.TenantBusinessType
	if rf, ok := ret.Get(0).(func(*model.TenantBusinessType) *graphql.TenantBusinessType); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graphql.TenantBusinessType)
		}
	}

	return r0
}

// NewTenantBusinessTypeConverter creates a new instance of TenantBusinessTypeConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantBusinessTypeConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantBusinessTypeConverter {
	mock := &TenantBusinessTypeConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
