// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"

// WebhookService is an autogenerated mock type for the WebhookService type
type WebhookService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, applicationID
func (_m *WebhookService) Create(ctx context.Context, applicationID string, in model.ApplicationWebhookInput) (string, error) {
	ret := _m.Called(ctx, in, applicationID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, model.ApplicationWebhookInput, string) string); ok {
		r0 = rf(ctx, in, applicationID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.ApplicationWebhookInput, string) error); ok {
		r1 = rf(ctx, in, applicationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WebhookService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *WebhookService) Get(ctx context.Context, id string) (*model.ApplicationWebhook, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.ApplicationWebhook
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ApplicationWebhook); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationWebhook)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, applicationID
func (_m *WebhookService) List(ctx context.Context, applicationID string) ([]*model.ApplicationWebhook, error) {
	ret := _m.Called(ctx, applicationID)

	var r0 []*model.ApplicationWebhook
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.ApplicationWebhook); ok {
		r0 = rf(ctx, applicationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ApplicationWebhook)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, applicationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, in
func (_m *WebhookService) Update(ctx context.Context, id string, in model.ApplicationWebhookInput) error {
	ret := _m.Called(ctx, id, in)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ApplicationWebhookInput) error); ok {
		r0 = rf(ctx, id, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
