// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// DestinationRepository is an autogenerated mock type for the destinationRepository type
type DestinationRepository struct {
	mock.Mock
}

// CreateDestination provides a mock function with given fields: ctx, _a1
func (_m *DestinationRepository) CreateDestination(ctx context.Context, _a1 *model.Destination) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Destination) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByTenantIDAndAssignmentID provides a mock function with given fields: ctx, tenantID, formationAssignmentID
func (_m *DestinationRepository) DeleteByTenantIDAndAssignmentID(ctx context.Context, tenantID string, formationAssignmentID string) error {
	ret := _m.Called(ctx, tenantID, formationAssignmentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tenantID, formationAssignmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByTenantIDAndAssignmentID provides a mock function with given fields: ctx, tenantID, formationAssignmentID
func (_m *DestinationRepository) ListByTenantIDAndAssignmentID(ctx context.Context, tenantID string, formationAssignmentID string) ([]*model.Destination, error) {
	ret := _m.Called(ctx, tenantID, formationAssignmentID)

	var r0 []*model.Destination
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*model.Destination); ok {
		r0 = rf(ctx, tenantID, formationAssignmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Destination)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, formationAssignmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDestinationRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewDestinationRepository creates a new instance of DestinationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDestinationRepository(t mockConstructorTestingTNewDestinationRepository) *DestinationRepository {
	mock := &DestinationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
