// Code generated by mockery. DO NOT EDIT.

package automock

import (
	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// IntegrationDepConverter is an autogenerated mock type for the IntegrationDepConverter type
type IntegrationDepConverter struct {
	mock.Mock
}

// InputFromGraphQL provides a mock function with given fields: in
func (_m *IntegrationDepConverter) InputFromGraphQL(in *graphql.IntegrationDependencyInput) (*model.IntegrationDependencyInput, error) {
	ret := _m.Called(in)

	var r0 *model.IntegrationDependencyInput
	var r1 error
	if rf, ok := ret.Get(0).(func(*graphql.IntegrationDependencyInput) (*model.IntegrationDependencyInput, error)); ok {
		return rf(in)
	}
	if rf, ok := ret.Get(0).(func(*graphql.IntegrationDependencyInput) *model.IntegrationDependencyInput); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IntegrationDependencyInput)
		}
	}

	if rf, ok := ret.Get(1).(func(*graphql.IntegrationDependencyInput) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToGraphQL provides a mock function with given fields: in, aspects, aspectEventResourcesByAspectID
func (_m *IntegrationDepConverter) ToGraphQL(in *model.IntegrationDependency, aspects []*model.Aspect, aspectEventResourcesByAspectID map[string][]*model.AspectEventResource) (*graphql.IntegrationDependency, error) {
	ret := _m.Called(in, aspects, aspectEventResourcesByAspectID)

	var r0 *graphql.IntegrationDependency
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.IntegrationDependency, []*model.Aspect, map[string][]*model.AspectEventResource) (*graphql.IntegrationDependency, error)); ok {
		return rf(in, aspects, aspectEventResourcesByAspectID)
	}
	if rf, ok := ret.Get(0).(func(*model.IntegrationDependency, []*model.Aspect, map[string][]*model.AspectEventResource) *graphql.IntegrationDependency); ok {
		r0 = rf(in, aspects, aspectEventResourcesByAspectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graphql.IntegrationDependency)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.IntegrationDependency, []*model.Aspect, map[string][]*model.AspectEventResource) error); ok {
		r1 = rf(in, aspects, aspectEventResourcesByAspectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIntegrationDepConverter creates a new instance of IntegrationDepConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationDepConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationDepConverter {
	mock := &IntegrationDepConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
