// Code generated by mockery. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"

	resource "github.com/kyma-incubator/compass/components/director/pkg/resource"
)

// IntegrationDependencyRepository is an autogenerated mock type for the IntegrationDependencyRepository type
type IntegrationDependencyRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tenant, item
func (_m *IntegrationDependencyRepository) Create(ctx context.Context, tenant string, item *model.IntegrationDependency) error {
	ret := _m.Called(ctx, tenant, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.IntegrationDependency) error); ok {
		r0 = rf(ctx, tenant, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateGlobal provides a mock function with given fields: ctx, item
func (_m *IntegrationDependencyRepository) CreateGlobal(ctx context.Context, item *model.IntegrationDependency) error {
	ret := _m.Called(ctx, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.IntegrationDependency) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tenantID, id
func (_m *IntegrationDependencyRepository) Delete(ctx context.Context, tenantID string, id string) error {
	ret := _m.Called(ctx, tenantID, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteGlobal provides a mock function with given fields: ctx, id
func (_m *IntegrationDependencyRepository) DeleteGlobal(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, tenantID, id
func (_m *IntegrationDependencyRepository) GetByID(ctx context.Context, tenantID string, id string) (*model.IntegrationDependency, error) {
	ret := _m.Called(ctx, tenantID, id)

	var r0 *model.IntegrationDependency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.IntegrationDependency, error)); ok {
		return rf(ctx, tenantID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.IntegrationDependency); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IntegrationDependency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDGlobal provides a mock function with given fields: ctx, id
func (_m *IntegrationDependencyRepository) GetByIDGlobal(ctx context.Context, id string) (*model.IntegrationDependency, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.IntegrationDependency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.IntegrationDependency, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.IntegrationDependency); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IntegrationDependency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByResourceID provides a mock function with given fields: ctx, tenantID, resourceType, resourceID
func (_m *IntegrationDependencyRepository) ListByResourceID(ctx context.Context, tenantID string, resourceType resource.Type, resourceID string) ([]*model.IntegrationDependency, error) {
	ret := _m.Called(ctx, tenantID, resourceType, resourceID)

	var r0 []*model.IntegrationDependency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, resource.Type, string) ([]*model.IntegrationDependency, error)); ok {
		return rf(ctx, tenantID, resourceType, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, resource.Type, string) []*model.IntegrationDependency); ok {
		r0 = rf(ctx, tenantID, resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.IntegrationDependency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, resource.Type, string) error); ok {
		r1 = rf(ctx, tenantID, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tenant, item
func (_m *IntegrationDependencyRepository) Update(ctx context.Context, tenant string, item *model.IntegrationDependency) error {
	ret := _m.Called(ctx, tenant, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.IntegrationDependency) error); ok {
		r0 = rf(ctx, tenant, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGlobal provides a mock function with given fields: ctx, item
func (_m *IntegrationDependencyRepository) UpdateGlobal(ctx context.Context, item *model.IntegrationDependency) error {
	ret := _m.Called(ctx, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.IntegrationDependency) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIntegrationDependencyRepository creates a new instance of IntegrationDependencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationDependencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationDependencyRepository {
	mock := &IntegrationDependencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
