// Code generated by mockery v2.12.1. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ClientInstrumenter is an autogenerated mock type for the ClientInstrumenter type
type ClientInstrumenter struct {
	mock.Mock
}

// InstrumentClient provides a mock function with given fields: clientID, authFlow, details
func (_m *ClientInstrumenter) InstrumentClient(clientID string, authFlow string, details string) {
	_m.Called(clientID, authFlow, details)
}

// NewClientInstrumenter creates a new instance of ClientInstrumenter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientInstrumenter(t testing.TB) *ClientInstrumenter {
	mock := &ClientInstrumenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
