{
 "title": "Kyma Environment Broker",
 "tags": [ "kyma-environment-broker" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Runtime Business Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration [s]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Gothreads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{service=\"compass-kyma-environment-broker\"}[30s])",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{service=\"compass-kyma-environment-broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"compass-kyma-environment-broker.*\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{container_name}}"
      },
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"compass-kyma-environment-broker.*\"}",
       "legendFormat": "Requested: {{container}}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"compass-kyma-environment-broker.*\"}",
       "legendFormat": "Limit: {{container}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"compass-kyma-environment-broker.*\"}[1m]))",
       "legendFormat": "{{container_name}}"
      },
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"compass-kyma-environment-broker.*\"}",
       "legendFormat": "Requested: {{container}}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"compass-kyma-environment-broker.*\"}",
       "legendFormat": "Limit: {{container}}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"compass-kyma-environment-broker.*\"}[1m])))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}