// Code generated by mockery v2.10.5. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// HealthCheckRepository is an autogenerated mock type for the HealthCheckRepository type
type HealthCheckRepository struct {
	mock.Mock
}
