// Code generated by mockery. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// HealthCheckRepository is an autogenerated mock type for the HealthCheckRepository type
type HealthCheckRepository struct {
	mock.Mock
}

// NewHealthCheckRepository creates a new instance of HealthCheckRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheckRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheckRepository {
	mock := &HealthCheckRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
