// Code generated by mockery v1.1.2. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// HealthCheckService is an autogenerated mock type for the HealthCheckService type
type HealthCheckService struct {
	mock.Mock
}
