// Code generated by mockery (devel). DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// HealthCheckService is an autogenerated mock type for the HealthCheckService type
type HealthCheckService struct {
	mock.Mock
}
