// Code generated by protoc-gen-go. DO NOT EDIT.
// source: director.proto

package director

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FilterOperator int32

const (
	FilterOperator_ALL FilterOperator = 0
	FilterOperator_ANY FilterOperator = 1
)

var FilterOperator_name = map[int32]string{
	0: "ALL",
	1: "ANY",
}
var FilterOperator_value = map[string]int32{
	"ALL": 0,
	"ANY": 1,
}

func (x FilterOperator) String() string {
	return proto.EnumName(FilterOperator_name, int32(x))
}
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{0}
}

type ApplicationStatusCondition int32

const (
	ApplicationStatusCondition_INITIAL ApplicationStatusCondition = 0
	ApplicationStatusCondition_UNKNOWN ApplicationStatusCondition = 1
	ApplicationStatusCondition_READY   ApplicationStatusCondition = 2
	ApplicationStatusCondition_FAILED  ApplicationStatusCondition = 3
)

var ApplicationStatusCondition_name = map[int32]string{
	0: "INITIAL",
	1: "UNKNOWN",
	2: "READY",
	3: "FAILED",
}
var ApplicationStatusCondition_value = map[string]int32{
	"INITIAL": 0,
	"UNKNOWN": 1,
	"READY":   2,
	"FAILED":  3,
}

func (x ApplicationStatusCondition) String() string {
	return proto.EnumName(ApplicationStatusCondition_name, int32(x))
}
func (ApplicationStatusCondition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{1}
}

type ApplicationsInput struct {
	LabelFilter          *LabelFilter `protobuf:"bytes,1,opt,name=labelFilter" json:"labelFilter,omitempty"`
	LabelsKey            string       `protobuf:"bytes,2,opt,name=labelsKey" json:"labelsKey,omitempty"`
	AnnotationsKey       string       `protobuf:"bytes,3,opt,name=annotationsKey" json:"annotationsKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ApplicationsInput) Reset()         { *m = ApplicationsInput{} }
func (m *ApplicationsInput) String() string { return proto.CompactTextString(m) }
func (*ApplicationsInput) ProtoMessage()    {}
func (*ApplicationsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{0}
}
func (m *ApplicationsInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationsInput.Unmarshal(m, b)
}
func (m *ApplicationsInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationsInput.Marshal(b, m, deterministic)
}
func (dst *ApplicationsInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationsInput.Merge(dst, src)
}
func (m *ApplicationsInput) XXX_Size() int {
	return xxx_messageInfo_ApplicationsInput.Size(m)
}
func (m *ApplicationsInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationsInput.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationsInput proto.InternalMessageInfo

func (m *ApplicationsInput) GetLabelFilter() *LabelFilter {
	if m != nil {
		return m.LabelFilter
	}
	return nil
}

func (m *ApplicationsInput) GetLabelsKey() string {
	if m != nil {
		return m.LabelsKey
	}
	return ""
}

func (m *ApplicationsInput) GetAnnotationsKey() string {
	if m != nil {
		return m.AnnotationsKey
	}
	return ""
}

type LabelFilter struct {
	Label                string         `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Values               []string       `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	FilterOperator       FilterOperator `protobuf:"varint,3,opt,name=filterOperator,enum=director.FilterOperator" json:"filterOperator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LabelFilter) Reset()         { *m = LabelFilter{} }
func (m *LabelFilter) String() string { return proto.CompactTextString(m) }
func (*LabelFilter) ProtoMessage()    {}
func (*LabelFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{1}
}
func (m *LabelFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelFilter.Unmarshal(m, b)
}
func (m *LabelFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelFilter.Marshal(b, m, deterministic)
}
func (dst *LabelFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelFilter.Merge(dst, src)
}
func (m *LabelFilter) XXX_Size() int {
	return xxx_messageInfo_LabelFilter.Size(m)
}
func (m *LabelFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelFilter.DiscardUnknown(m)
}

var xxx_messageInfo_LabelFilter proto.InternalMessageInfo

func (m *LabelFilter) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *LabelFilter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *LabelFilter) GetFilterOperator() FilterOperator {
	if m != nil {
		return m.FilterOperator
	}
	return FilterOperator_ALL
}

type ApplicationStatus struct {
	Condition            ApplicationStatusCondition `protobuf:"varint,1,opt,name=condition,enum=director.ApplicationStatusCondition" json:"condition,omitempty"`
	Timestamp            int64                      `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ApplicationStatus) Reset()         { *m = ApplicationStatus{} }
func (m *ApplicationStatus) String() string { return proto.CompactTextString(m) }
func (*ApplicationStatus) ProtoMessage()    {}
func (*ApplicationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{2}
}
func (m *ApplicationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationStatus.Unmarshal(m, b)
}
func (m *ApplicationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationStatus.Marshal(b, m, deterministic)
}
func (dst *ApplicationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationStatus.Merge(dst, src)
}
func (m *ApplicationStatus) XXX_Size() int {
	return xxx_messageInfo_ApplicationStatus.Size(m)
}
func (m *ApplicationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationStatus proto.InternalMessageInfo

func (m *ApplicationStatus) GetCondition() ApplicationStatusCondition {
	if m != nil {
		return m.Condition
	}
	return ApplicationStatusCondition_INITIAL
}

func (m *ApplicationStatus) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type APIDefinition struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	//  string spec = 2; //
	TargetURL            string   `protobuf:"bytes,2,opt,name=targetURL" json:"targetURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIDefinition) Reset()         { *m = APIDefinition{} }
func (m *APIDefinition) String() string { return proto.CompactTextString(m) }
func (*APIDefinition) ProtoMessage()    {}
func (*APIDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{3}
}
func (m *APIDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIDefinition.Unmarshal(m, b)
}
func (m *APIDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIDefinition.Marshal(b, m, deterministic)
}
func (dst *APIDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIDefinition.Merge(dst, src)
}
func (m *APIDefinition) XXX_Size() int {
	return xxx_messageInfo_APIDefinition.Size(m)
}
func (m *APIDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_APIDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_APIDefinition proto.InternalMessageInfo

func (m *APIDefinition) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *APIDefinition) GetTargetURL() string {
	if m != nil {
		return m.TargetURL
	}
	return ""
}

type Application struct {
	Id          string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tenant      string             `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
	Name        string             `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string             `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Labels      map[string]string  `protobuf:"bytes,5,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string][]byte  `protobuf:"bytes,6,rep,name=annotations" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status      *ApplicationStatus `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	//  repeated ApplicationWebhook webhooks = 8;
	HealthCheckURL       string           `protobuf:"bytes,9,opt,name=healthCheckURL" json:"healthCheckURL,omitempty"`
	Apis                 []*APIDefinition `protobuf:"bytes,10,rep,name=apis" json:"apis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{4}
}
func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (dst *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(dst, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Application) GetAnnotations() map[string][]byte {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Application) GetStatus() *ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Application) GetHealthCheckURL() string {
	if m != nil {
		return m.HealthCheckURL
	}
	return ""
}

func (m *Application) GetApis() []*APIDefinition {
	if m != nil {
		return m.Apis
	}
	return nil
}

type ApplicationsResponse struct {
	Applications         []*Application `protobuf:"bytes,1,rep,name=applications" json:"applications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApplicationsResponse) Reset()         { *m = ApplicationsResponse{} }
func (m *ApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationsResponse) ProtoMessage()    {}
func (*ApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{5}
}
func (m *ApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationsResponse.Unmarshal(m, b)
}
func (m *ApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationsResponse.Marshal(b, m, deterministic)
}
func (dst *ApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationsResponse.Merge(dst, src)
}
func (m *ApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationsResponse.Size(m)
}
func (m *ApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationsResponse proto.InternalMessageInfo

func (m *ApplicationsResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type ApplicationRoot struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationRoot) Reset()         { *m = ApplicationRoot{} }
func (m *ApplicationRoot) String() string { return proto.CompactTextString(m) }
func (*ApplicationRoot) ProtoMessage()    {}
func (*ApplicationRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{6}
}
func (m *ApplicationRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationRoot.Unmarshal(m, b)
}
func (m *ApplicationRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationRoot.Marshal(b, m, deterministic)
}
func (dst *ApplicationRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationRoot.Merge(dst, src)
}
func (m *ApplicationRoot) XXX_Size() int {
	return xxx_messageInfo_ApplicationRoot.Size(m)
}
func (m *ApplicationRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationRoot.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationRoot proto.InternalMessageInfo

func (m *ApplicationRoot) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ApplicationApi struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	TargetURL            string   `protobuf:"bytes,2,opt,name=targetURL" json:"targetURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationApi) Reset()         { *m = ApplicationApi{} }
func (m *ApplicationApi) String() string { return proto.CompactTextString(m) }
func (*ApplicationApi) ProtoMessage()    {}
func (*ApplicationApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{7}
}
func (m *ApplicationApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationApi.Unmarshal(m, b)
}
func (m *ApplicationApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationApi.Marshal(b, m, deterministic)
}
func (dst *ApplicationApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationApi.Merge(dst, src)
}
func (m *ApplicationApi) XXX_Size() int {
	return xxx_messageInfo_ApplicationApi.Size(m)
}
func (m *ApplicationApi) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationApi.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationApi proto.InternalMessageInfo

func (m *ApplicationApi) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ApplicationApi) GetTargetURL() string {
	if m != nil {
		return m.TargetURL
	}
	return ""
}

type ApplicationApisResult struct {
	ApplicationApis      []*ApplicationApi `protobuf:"bytes,1,rep,name=applicationApis" json:"applicationApis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApplicationApisResult) Reset()         { *m = ApplicationApisResult{} }
func (m *ApplicationApisResult) String() string { return proto.CompactTextString(m) }
func (*ApplicationApisResult) ProtoMessage()    {}
func (*ApplicationApisResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_director_586bed6d70511026, []int{8}
}
func (m *ApplicationApisResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationApisResult.Unmarshal(m, b)
}
func (m *ApplicationApisResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationApisResult.Marshal(b, m, deterministic)
}
func (dst *ApplicationApisResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationApisResult.Merge(dst, src)
}
func (m *ApplicationApisResult) XXX_Size() int {
	return xxx_messageInfo_ApplicationApisResult.Size(m)
}
func (m *ApplicationApisResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationApisResult.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationApisResult proto.InternalMessageInfo

func (m *ApplicationApisResult) GetApplicationApis() []*ApplicationApi {
	if m != nil {
		return m.ApplicationApis
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplicationsInput)(nil), "director.ApplicationsInput")
	proto.RegisterType((*LabelFilter)(nil), "director.LabelFilter")
	proto.RegisterType((*ApplicationStatus)(nil), "director.ApplicationStatus")
	proto.RegisterType((*APIDefinition)(nil), "director.APIDefinition")
	proto.RegisterType((*Application)(nil), "director.Application")
	proto.RegisterMapType((map[string][]byte)(nil), "director.Application.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "director.Application.LabelsEntry")
	proto.RegisterType((*ApplicationsResponse)(nil), "director.ApplicationsResponse")
	proto.RegisterType((*ApplicationRoot)(nil), "director.ApplicationRoot")
	proto.RegisterType((*ApplicationApi)(nil), "director.ApplicationApi")
	proto.RegisterType((*ApplicationApisResult)(nil), "director.ApplicationApisResult")
	proto.RegisterEnum("director.FilterOperator", FilterOperator_name, FilterOperator_value)
	proto.RegisterEnum("director.ApplicationStatusCondition", ApplicationStatusCondition_name, ApplicationStatusCondition_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectorClient is the client API for Director service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectorClient interface {
	Applications(ctx context.Context, in *ApplicationsInput, opts ...grpc.CallOption) (*ApplicationsResponse, error)
	Apis(ctx context.Context, in *ApplicationRoot, opts ...grpc.CallOption) (*ApplicationApisResult, error)
}

type directorClient struct {
	cc *grpc.ClientConn
}

func NewDirectorClient(cc *grpc.ClientConn) DirectorClient {
	return &directorClient{cc}
}

func (c *directorClient) Applications(ctx context.Context, in *ApplicationsInput, opts ...grpc.CallOption) (*ApplicationsResponse, error) {
	out := new(ApplicationsResponse)
	err := c.cc.Invoke(ctx, "/director.Director/Applications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) Apis(ctx context.Context, in *ApplicationRoot, opts ...grpc.CallOption) (*ApplicationApisResult, error) {
	out := new(ApplicationApisResult)
	err := c.cc.Invoke(ctx, "/director.Director/Apis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Director service

type DirectorServer interface {
	Applications(context.Context, *ApplicationsInput) (*ApplicationsResponse, error)
	Apis(context.Context, *ApplicationRoot) (*ApplicationApisResult, error)
}

func RegisterDirectorServer(s *grpc.Server, srv DirectorServer) {
	s.RegisterService(&_Director_serviceDesc, srv)
}

func _Director_Applications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).Applications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.Director/Applications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).Applications(ctx, req.(*ApplicationsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_Apis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationRoot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).Apis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.Director/Apis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).Apis(ctx, req.(*ApplicationRoot))
	}
	return interceptor(ctx, in, info, handler)
}

var _Director_serviceDesc = grpc.ServiceDesc{
	ServiceName: "director.Director",
	HandlerType: (*DirectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Applications",
			Handler:    _Director_Applications_Handler,
		},
		{
			MethodName: "Apis",
			Handler:    _Director_Apis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "director.proto",
}

func init() { proto.RegisterFile("director.proto", fileDescriptor_director_586bed6d70511026) }

var fileDescriptor_director_586bed6d70511026 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xd1, 0x4e, 0xdb, 0x4a,
	0x10, 0xc5, 0x71, 0x70, 0xf0, 0x98, 0x6b, 0x7c, 0x47, 0xc0, 0xf5, 0x4d, 0xab, 0x36, 0x58, 0x15,
	0x8a, 0xa8, 0xc4, 0x43, 0x78, 0x68, 0xa9, 0x54, 0x54, 0x83, 0x41, 0xb5, 0x08, 0xa1, 0xdd, 0x16,
	0x55, 0xa8, 0x4f, 0x4b, 0xb2, 0x14, 0x0b, 0x63, 0x5b, 0xf6, 0xa6, 0x12, 0x0f, 0xfd, 0x89, 0xfe,
	0x40, 0xbf, 0xb2, 0xef, 0x95, 0xd7, 0x0e, 0x5e, 0x07, 0x53, 0xde, 0x3c, 0x33, 0xe7, 0xec, 0xce,
	0x9c, 0x39, 0x6b, 0x30, 0x27, 0x41, 0xca, 0xc6, 0x3c, 0x4e, 0xb7, 0x93, 0x34, 0xe6, 0x31, 0x2e,
	0xcd, 0x62, 0xe7, 0xa7, 0x02, 0xff, 0xba, 0x49, 0x12, 0x06, 0x63, 0xca, 0x83, 0x38, 0xca, 0xfc,
	0x28, 0x99, 0x72, 0x7c, 0x05, 0x46, 0x48, 0x2f, 0x58, 0x78, 0x14, 0x84, 0x9c, 0xa5, 0xb6, 0xd2,
	0x53, 0xfa, 0xc6, 0x60, 0x6d, 0xfb, 0xee, 0x94, 0x61, 0x55, 0x24, 0x32, 0x12, 0x9f, 0x82, 0x2e,
	0xc2, 0xec, 0x98, 0xdd, 0xda, 0xad, 0x9e, 0xd2, 0xd7, 0x49, 0x95, 0xc0, 0x4d, 0x30, 0x69, 0x14,
	0xc5, 0xbc, 0xb8, 0x2a, 0x87, 0xa8, 0x02, 0x32, 0x97, 0x75, 0x7e, 0x80, 0x21, 0xdd, 0x80, 0xab,
	0xb0, 0x28, 0xce, 0x10, 0x7d, 0xe8, 0xa4, 0x08, 0x70, 0x1d, 0xb4, 0xef, 0x34, 0x9c, 0xb2, 0xcc,
	0x6e, 0xf5, 0xd4, 0xbe, 0x4e, 0xca, 0x08, 0xdf, 0x81, 0x79, 0x29, 0x78, 0xa7, 0x09, 0x4b, 0x29,
	0x8f, 0x53, 0x71, 0x89, 0x39, 0xb0, 0xab, 0xf6, 0x8f, 0x6a, 0x75, 0x32, 0x87, 0x77, 0xa6, 0x35,
	0x49, 0x3e, 0x71, 0xca, 0xa7, 0x19, 0xee, 0x83, 0x3e, 0x8e, 0xa3, 0x49, 0x90, 0xa7, 0x44, 0x23,
	0xe6, 0xe0, 0x45, 0x75, 0xe2, 0x3d, 0xfc, 0xc1, 0x0c, 0x4b, 0x2a, 0x5a, 0xae, 0x0e, 0x0f, 0x6e,
	0x58, 0xc6, 0xe9, 0x4d, 0x22, 0xd4, 0x51, 0x49, 0x95, 0x70, 0xde, 0xc2, 0x3f, 0xee, 0x07, 0xdf,
	0x63, 0x97, 0x41, 0x54, 0xc0, 0x4d, 0x68, 0x05, 0x93, 0x72, 0xe8, 0x56, 0x30, 0x11, 0x74, 0x9a,
	0x7e, 0x63, 0xfc, 0x8c, 0x0c, 0x67, 0xe2, 0xde, 0x25, 0x9c, 0xdf, 0x2a, 0x18, 0x52, 0x1b, 0xf7,
	0xd8, 0xeb, 0xa0, 0x71, 0x16, 0xd1, 0x88, 0x97, 0xd4, 0x32, 0x42, 0x84, 0x76, 0x44, 0x6f, 0x58,
	0xb9, 0x0a, 0xf1, 0x8d, 0x3d, 0x30, 0x26, 0x2c, 0x1b, 0xa7, 0x41, 0x22, 0xc6, 0x6d, 0x8b, 0x92,
	0x9c, 0xc2, 0x5d, 0xd0, 0x8a, 0xbd, 0xda, 0x8b, 0x3d, 0xb5, 0x6f, 0x0c, 0x36, 0x1a, 0xb5, 0x28,
	0x8c, 0x92, 0x1d, 0x46, 0x3c, 0xbd, 0x25, 0x25, 0x01, 0xdf, 0x83, 0x21, 0xed, 0xdb, 0xd6, 0x04,
	0x7f, 0xb3, 0x99, 0xef, 0x56, 0xc0, 0xe2, 0x10, 0x99, 0x8a, 0x3b, 0xa0, 0x65, 0x42, 0x6d, 0xbb,
	0x23, 0x1c, 0xfa, 0xe4, 0x2f, 0x0b, 0x21, 0x25, 0x34, 0x37, 0xe1, 0x15, 0xa3, 0x21, 0xbf, 0x3a,
	0xb8, 0x62, 0xe3, 0xeb, 0x5c, 0x4a, 0xbd, 0x30, 0x61, 0x3d, 0x8b, 0x2f, 0xa1, 0x4d, 0x93, 0x20,
	0xb3, 0x41, 0xf4, 0xf7, 0x9f, 0x74, 0xb4, 0xbc, 0x24, 0x22, 0x40, 0xdd, 0xdd, 0xd2, 0xb1, 0x45,
	0x97, 0x68, 0x81, 0x7a, 0xcd, 0x6e, 0x4b, 0xf1, 0xf3, 0xcf, 0xdc, 0xc3, 0xc2, 0x9f, 0xa5, 0xf8,
	0x45, 0xf0, 0xa6, 0xf5, 0x5a, 0xe9, 0xee, 0x81, 0x35, 0x3f, 0xe5, 0x63, 0xfc, 0x65, 0x89, 0xef,
	0x7c, 0x84, 0x55, 0xf9, 0x01, 0x13, 0x96, 0x25, 0x71, 0x94, 0x31, 0xdc, 0x85, 0x65, 0x2a, 0xe5,
	0x6d, 0x45, 0xcc, 0xb1, 0xd6, 0x28, 0x11, 0xa9, 0x41, 0x9d, 0x0d, 0x58, 0x91, 0x8b, 0x71, 0xcc,
	0x73, 0x37, 0xf9, 0xde, 0xcc, 0x4d, 0xbe, 0xe7, 0xec, 0x81, 0x29, 0x41, 0xdc, 0x24, 0x98, 0x47,
	0x3c, 0xe2, 0xd6, 0xaf, 0xb0, 0x56, 0xe7, 0xe7, 0x8d, 0x4f, 0x43, 0x8e, 0xfb, 0xb0, 0x42, 0xeb,
	0x85, 0xb2, 0x73, 0xbb, 0xb1, 0x73, 0x37, 0x09, 0xc8, 0x3c, 0x61, 0xcb, 0x01, 0xb3, 0xfe, 0xc4,
	0xb1, 0x03, 0xaa, 0x3b, 0x1c, 0x5a, 0x0b, 0xe2, 0x63, 0x74, 0x6e, 0x29, 0x5b, 0x27, 0xd0, 0x7d,
	0xf8, 0xd1, 0xa2, 0x01, 0x1d, 0x7f, 0xe4, 0x7f, 0xf6, 0xdd, 0x9c, 0x63, 0x40, 0xe7, 0x6c, 0x74,
	0x3c, 0x3a, 0xfd, 0x32, 0xb2, 0x14, 0xd4, 0x61, 0x91, 0x1c, 0xba, 0xde, 0xb9, 0xd5, 0x42, 0x00,
	0xed, 0xc8, 0xf5, 0x87, 0x87, 0x9e, 0xa5, 0x0e, 0x7e, 0x29, 0xb0, 0xe4, 0x95, 0xfd, 0xe1, 0x09,
	0x2c, 0xcb, 0x2b, 0xc1, 0x66, 0x5f, 0x16, 0xff, 0xda, 0xee, 0xb3, 0xe6, 0xe2, 0x6c, 0x8f, 0xce,
	0x02, 0x7a, 0xd0, 0xce, 0xc7, 0xc2, 0xff, 0x9b, 0x77, 0x17, 0xc7, 0xbc, 0xfb, 0xfc, 0x21, 0x71,
	0x4a, 0x59, 0x9d, 0x85, 0x0b, 0x4d, 0xfc, 0xfa, 0x77, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x83,
	0xfd, 0xc8, 0xf0, 0x0c, 0x06, 0x00, 0x00,
}
