// Code generated by mockery. DO NOT EDIT.

package automock

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// TokenData is an autogenerated mock type for the TokenData type
type TokenData struct {
	mock.Mock
}

// Claims provides a mock function with given fields: v
func (_m *TokenData) Claims(v interface{}) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenData creates a new instance of TokenData. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenData(t testing.TB) *TokenData {
	mock := &TokenData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
