// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MetricsPusher is an autogenerated mock type for the MetricsPusher type
type MetricsPusher struct {
	mock.Mock
}

// RecordEventingRequest provides a mock function with given fields: method, res
func (_m *MetricsPusher) RecordEventingRequest(method string, res *http.Response) {
	_m.Called(method, res)
}
